packages:
  - './'
  - './example'
  - './tests/functional-tests'

allowBuilds:
  esbuild: true

ignoreWorkspaceRootCheck: true
loglevel: debug

publicHoistPattern:
  - '*eslint*'
  - 'typescript-eslint'
