name: Analyze Commit Messages
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write
jobs:
  analyze-commits:
    name: Generate docs and coverage report
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/analyze-commits.yml@0de982832e53cff28e272cee33547b039f5193c8
    with:
      previewNotes: false

  preview-changeset:
    name: Preview changeset
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/preview-changeset-release.yml@0de982832e53cff28e272cee33547b039f5193c8
    with:
      pr-title: ${{ github.event.pull_request.title }}

