name: Generate docs and coverage report

on:
  push:
    branches:
      - main

jobs:
  coverage-report:
    name: Coverage report
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/docs-and-coverage.yml@v1
